### ISSUE TITLE
search feature is highly case sensitive

### ISSUE THREAD

**Issue by Arsenic-ATG** [HimeshNayak/Hackathons-Portfolio-App#10]
to search for any skill one have to keep the first letter of the keyword capital. I don't think people will take it into consideration while searching.
ideally search function should be case insensitive.

here is a screenshot where I tried to search for ```python``` instead of **P**ython and it showed no result.

![Screenshot_20200725-141607507](https://user-images.githubusercontent.com/54987647/88453125-07ca7300-ce82-11ea-91b4-d366839b822a.jpg)

**Comment by HimeshNayak** [comment]
Hi, @Arsenic-ATG 
We had come across this issue and would fix it in the next update. Thanks for the feedback!
