### ISSUE TITLE
Mobile view is meh in portfolio

### ISSUE THREAD

**Issue by Unnatmalkoti** [HimeshNayak/Hackathons-Portfolio-App#9]
![Screenshot_2020-06-22-21-49-27-156_com android browser](https://user-images.githubusercontent.com/39382275/85590489-14c92c00-b662-11ea-8f3b-0d5aab46ef74.jpg)

**Comment by HimeshNayak** [comment]
This is the issue of the website and not app. I think you have posted the issue in wrong repository.

**Comment by Unnatmalkoti** [comment]
Owops my bad
